services:
  tests:
    image: buildkite/plugin-tester:v4.1.0
    volumes:
      - '.:/plugin:ro'
    environment:
      - BUILDKITE_PLUGIN_DOCKER_ECR_CACHE_ECR_TAGS_MYKEY=mykeyvalue
  lint:
    image: buildkite/plugin-linter
    command: ['--name', 'seek-oss/docker-ecr-cache']
    volumes:
      - '.:/plugin:ro'
